### ISSUE TITLE
Acrylic effect is barely visible, Slower performance, Weird looking dark theme and server banners look bad

### ISSUE THREAD

**Issue by Void48** [xirreal/Acrylic#1]
Please give us the option to use the default Discord theme and just use Acrylic effect alone. 
Also, here's how the server banners look btw.: 
![image](https://user-images.githubusercontent.com/85196642/132067436-a93b6832-8e55-41c1-9234-20df2e2bb16f.png)

**Comment by xirreal** [comment]
1. You can use the discord default theme. It's not documented yet but there's a settings api exposed through the global "acrylic" object.
Open discord console and type acrylic.updateSettings("injectCss", false)

2. Performance is not something I can control. Due to a bug in Windows, accessing acrylic effects through win32 api will cause a slow down when you have a mouse with a high polling rate. A workaround is lowering the polling rate to 500hz, or using the blurType number 2 (simple blur instead of acrylic).

3. The theme needs to be updated, I just cant keep up with discord's updates.

4. Server banners look like that cause of the z-index. Will be fixed in the future.

**Comment by Void48** [comment]
> 1. You can use the discord default theme. It's not documented yet but there's a settings api exposed through the global "acrylic" object.
>    Open discord console and type acrylic.updateSettings("injectCss", false)
> 2. Performance is not something I can control. Due to a bug in Windows, accessing acrylic effects through win32 api will cause a slow down when you have a mouse with a high polling rate. A workaround is lowering the polling rate to 500hz, or using the blurType number 2 (simple blur instead of acrylic).
> 3. The theme needs to be updated, I just cant keep up with discord's updates.
> 4. Server banners look like that cause of the z-index. Will be fixed in the future.

Thanks :)
